// GENERATED by scripts/generate-checks.py from the sloptic catalog. Do not edit by hand.
// Facts only: which categories exist, how many checks each holds, and which run without
// verification. Human labels live in check-labels.ts.

export type Area = "security" | "qa" | "performance";
/** open: every check runs on any URL. gated: every check needs verification. mixed: some of each. */
export type Access = "open" | "gated" | "mixed";

export type CategoryFact = {
  slug: string;
  area: Area;
  probes: number;
  passive: number;
  access: Access;
};

export const CATEGORY_FACTS: CategoryFact[] = [
  { slug: "caching", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "compression", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "load-resilience", area: "performance", probes: 1, passive: 0, access: "gated" },
  { slug: "load-time", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "page-weight", area: "performance", probes: 2, passive: 2, access: "open" },
  { slug: "request-count", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "speed", area: "performance", probes: 3, passive: 3, access: "open" },
  { slug: "web-vitals", area: "performance", probes: 2, passive: 2, access: "open" },
  { slug: "accessibility", area: "qa", probes: 2, passive: 2, access: "open" },
  { slug: "broken-links", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "console-errors", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "content-type", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "crash-resistance", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "data-integrity", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "dead-controls", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "deployment-hygiene", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "error-hygiene", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "http-conformance", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "http-correctness", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "input-validation", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "race-condition", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "seo", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "ui-honesty", area: "qa", probes: 5, passive: 3, access: "mixed" },
  { slug: "access-control", area: "security", probes: 7, passive: 0, access: "gated" },
  { slug: "backend-exposure", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "command-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "cors", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "csrf", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "data-exposure", area: "security", probes: 2, passive: 1, access: "mixed" },
  { slug: "debug-mode", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "dependency", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "dom-xss", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "dos-resistance", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "exposure", area: "security", probes: 6, passive: 1, access: "mixed" },
  { slug: "file-upload", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "filter-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "host-header", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "mixed-content", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "open-redirect", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "path-traversal", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "rate-limiting", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "response-splitting", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "secrets-exposure", area: "security", probes: 2, passive: 2, access: "open" },
  { slug: "security-headers", area: "security", probes: 7, passive: 7, access: "open" },
  { slug: "session", area: "security", probes: 4, passive: 0, access: "gated" },
  { slug: "session-management", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "sql-injection", area: "security", probes: 5, passive: 0, access: "gated" },
  { slug: "ssrf", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "template-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "xss", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "xxe", area: "security", probes: 1, passive: 0, access: "gated" },
];

export const TOTALS = { total: 91, passive: 37, active: 54 };
