// GENERATED by scripts/generate-checks.py from the sloptic catalog. Do not edit by hand.
// Facts only: which categories exist, how many checks each holds, and which run without
// verification. Human labels live in check-labels.ts.

export type Area = "security" | "qa" | "performance";
/** open: every check runs on any URL. gated: every check needs verification. mixed: some of each. */
export type Access = "open" | "gated" | "mixed";

export type CategoryFact = {
  slug: string;
  area: Area;
  probes: number;
  passive: number;
  access: Access;
};

export const CATEGORY_FACTS: CategoryFact[] = [
  { slug: "caching", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "dom-size", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "font-loading", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "lcp-strategy", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "load-resilience", area: "performance", probes: 1, passive: 0, access: "gated" },
  { slug: "load-time", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "minification", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "overall", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "page-weight", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "request-count", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "speed", area: "performance", probes: 1, passive: 1, access: "open" },
  { slug: "web-vitals", area: "performance", probes: 2, passive: 2, access: "open" },
  { slug: "accessibility", area: "qa", probes: 2, passive: 2, access: "open" },
  { slug: "availability", area: "qa", probes: 3, passive: 3, access: "open" },
  { slug: "broken-links", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "console-errors", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "content-type", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "crash-resistance", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "data-integrity", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "dead-controls", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "deployment-hygiene", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "email-verification", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "error-hygiene", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "http-conformance", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "http-correctness", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "input-validation", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "password-reset", area: "qa", probes: 1, passive: 0, access: "gated" },
  { slug: "race-condition", area: "qa", probes: 2, passive: 0, access: "gated" },
  { slug: "seo", area: "qa", probes: 1, passive: 1, access: "open" },
  { slug: "ui-honesty", area: "qa", probes: 5, passive: 3, access: "mixed" },
  { slug: "access-control", area: "security", probes: 7, passive: 0, access: "gated" },
  { slug: "backend-exposure", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "command-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "cors", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "csrf", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "data-exposure", area: "security", probes: 2, passive: 1, access: "mixed" },
  { slug: "debug-mode", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "dependency", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "dom-xss", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "dos-resistance", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "exposure", area: "security", probes: 7, passive: 2, access: "mixed" },
  { slug: "file-upload", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "filter-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "host-header", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "mixed-content", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "open-redirect", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "path-traversal", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "rate-limiting", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "response-splitting", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "secrets-exposure", area: "security", probes: 2, passive: 2, access: "open" },
  { slug: "security-headers", area: "security", probes: 7, passive: 7, access: "open" },
  { slug: "session", area: "security", probes: 4, passive: 0, access: "gated" },
  { slug: "session-management", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "sql-injection", area: "security", probes: 5, passive: 0, access: "gated" },
  { slug: "ssrf", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "supply-chain", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "template-injection", area: "security", probes: 1, passive: 0, access: "gated" },
  { slug: "transport-security", area: "security", probes: 1, passive: 1, access: "open" },
  { slug: "xss", area: "security", probes: 2, passive: 0, access: "gated" },
  { slug: "xxe", area: "security", probes: 1, passive: 0, access: "gated" },
];

export const TOTALS = { total: 102, passive: 44, active: 58 };

/** Passive probe id -> [area, kind]. Lets a report name the checks that passed, which the grade
 *  record lists by id only. Passive-only: the active ones never run on a graded target here. */
export const PASSIVE_PROBE_INDEX: Record<string, [Area, string]> = {
  "perf-cache-001": ["performance", "caching"],
  "perf-cwv-001": ["performance", "web-vitals"],
  "perf-cwv-002": ["performance", "web-vitals"],
  "perf-dom-001": ["performance", "dom-size"],
  "perf-font-001": ["performance", "font-loading"],
  "perf-lcp-001": ["performance", "lcp-strategy"],
  "perf-lighthouse-001": ["performance", "overall"],
  "perf-loadtime-001": ["performance", "load-time"],
  "perf-minify-001": ["performance", "minification"],
  "perf-requests-001": ["performance", "request-count"],
  "perf-ttfb-001": ["performance", "speed"],
  "perf-weight-001": ["performance", "page-weight"],
  "qa-a11y-001": ["qa", "accessibility"],
  "qa-a11y-002": ["qa", "accessibility"],
  "qa-backnav-001": ["qa", "ui-honesty"],
  "qa-chunk-001": ["qa", "ui-honesty"],
  "qa-console-001": ["qa", "console-errors"],
  "qa-ctype-001": ["qa", "content-type"],
  "qa-deeplink-001": ["qa", "ui-honesty"],
  "qa-deploy-001": ["qa", "availability"],
  "qa-deploy-002": ["qa", "availability"],
  "qa-deploy-003": ["qa", "availability"],
  "qa-devbuild-001": ["qa", "deployment-hygiene"],
  "qa-http-001": ["qa", "http-correctness"],
  "qa-http-002": ["qa", "http-conformance"],
  "qa-links-001": ["qa", "broken-links"],
  "qa-seo-001": ["qa", "seo"],
  "sec-cors-001": ["security", "cors"],
  "sec-csp-001": ["security", "security-headers"],
  "sec-deps-001": ["security", "dependency"],
  "sec-exposure-005": ["security", "data-exposure"],
  "sec-exposure-006": ["security", "exposure"],
  "sec-exposure-009": ["security", "exposure"],
  "sec-headers-001": ["security", "security-headers"],
  "sec-headers-002": ["security", "security-headers"],
  "sec-headers-003": ["security", "security-headers"],
  "sec-headers-004": ["security", "security-headers"],
  "sec-headers-005": ["security", "security-headers"],
  "sec-headers-006": ["security", "security-headers"],
  "sec-mixed-001": ["security", "mixed-content"],
  "sec-secrets-001": ["security", "secrets-exposure"],
  "sec-secrets-002": ["security", "secrets-exposure"],
  "sec-sri-001": ["security", "supply-chain"],
  "sec-tls-001": ["security", "transport-security"],
};
