#!/usr/bin/env python3
"""Emit the check facts the site displays, straight from the grader's catalog.

The web repo must not keep its own copy of what Sloptic checks: the moment a probe lands in
sloptic-main, a hand-maintained list here starts lying. So the FACTS (which categories exist, how
many probes each holds, and whether they run on any URL) are generated, and only the human LABELS
are written by hand, in web/lib/check-labels.ts.

Output is committed so the Vercel build never needs the sibling repo. Rerun after a catalog change
and drift shows up as a diff instead of silently going stale:

    python scripts/generate-checks.py            # ../sloptic-main alongside this repo
    python scripts/generate-checks.py --grader /path/to/sloptic-main
"""
from __future__ import annotations

import argparse
import pathlib
import sys
from collections import defaultdict

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "web" / "lib" / "checks.generated.ts"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--grader", default=str(HERE.parent.parent / "sloptic-main"),
                    help="path to the sloptic-main checkout")
    args = ap.parse_args()

    grader = pathlib.Path(args.grader).resolve()
    if not (grader / "sloptic").is_dir():
        print(f"no grader at {grader}. Pass --grader.", file=sys.stderr)
        return 1
    sys.path.insert(0, str(grader))

    from sloptic import safety                     # noqa: E402
    from sloptic.catalog import load_catalog       # noqa: E402

    probes = load_catalog(grader / "catalog")

    # Fail loudly rather than emit numbers that do not add up: safety.py is a hand-kept allow-list,
    # and if it ever stops partitioning the live catalog the site's counts become fiction.
    ids = {p.id for p in probes}
    classified = safety.PASSIVE_PROBES | safety.ACTIVE_PROBES
    if classified != ids or (safety.PASSIVE_PROBES & safety.ACTIVE_PROBES):
        print("safety.py no longer partitions the catalog; refusing to generate.", file=sys.stderr)
        print(f"  unclassified: {sorted(ids - classified)}", file=sys.stderr)
        print(f"  stale ids:    {sorted(classified - ids)}", file=sys.stderr)
        return 1

    cats: dict[tuple[str, str], list] = defaultdict(list)
    for p in probes:
        cats[(p.bundle, p.category)].append(p.id)

    rows = []
    for (area, slug), members in sorted(cats.items()):
        n = len(members)
        npass = sum(1 for i in members if safety.is_passive(i))
        access = "open" if npass == n else "gated" if npass == 0 else "mixed"
        rows.append({"slug": slug, "area": area, "probes": n, "passive": npass, "access": access})

    passive = len(safety.PASSIVE_PROBES)
    body = ",\n".join(
        f'  {{ slug: "{r["slug"]}", area: "{r["area"]}", probes: {r["probes"]}, '
        f'passive: {r["passive"]}, access: "{r["access"]}" }}'
        for r in rows
    )

    OUT.write_text(f'''// GENERATED by scripts/generate-checks.py from the sloptic catalog. Do not edit by hand.
// Facts only: which categories exist, how many checks each holds, and which run without
// verification. Human labels live in check-labels.ts.

export type Area = "security" | "qa" | "performance";
/** open: every check runs on any URL. gated: every check needs verification. mixed: some of each. */
export type Access = "open" | "gated" | "mixed";

export type CategoryFact = {{
  slug: string;
  area: Area;
  probes: number;
  passive: number;
  access: Access;
}};

export const CATEGORY_FACTS: CategoryFact[] = [
{body},
];

export const TOTALS = {{ total: {len(probes)}, passive: {passive}, active: {len(probes) - passive} }};
''')

    print(f"wrote {OUT.relative_to(HERE.parent)}")
    print(f"  {len(probes)} checks, {passive} passive, {len(rows)} categories")
    for area in ("security", "qa", "performance"):
        n = [r for r in rows if r["area"] == area]
        print(f"  {area}: {len(n)} categories, {sum(r['probes'] for r in n)} checks")
    mixed = [r["slug"] for r in rows if r["access"] == "mixed"]
    if mixed:
        print(f"  mixed access: {', '.join(mixed)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
